### ISSUE TITLE
Configure relation between plantuml  and gitlab

### ISSUE THREAD

**Issue by kannkyo** [kannkyo/arrows#11]

**Comment by kannkyo** [comment]
setup plantuml at gitlab GUI and curl from gitlab server.
But i get only error.

```shell
curl http://plantuml:8080/png/U9npoazIqBLJSCp9J4vLi5B8ICt9oUU2y832Ja1PAmNtV0N7yiHABW0XJWoz
```

```shell
plantuml_1                | 2019-01-03 19:00:16.573:WARN:oejs.HttpChannel:qtp2027961269-18: /png/U9npoazIqBLJSCp9J4vLi5B8ICt9oI_cWd21uav0QIi5ztm5n_B4IYu0ChGDC000
plantuml_1                | java.lang.NullPointerException
plantuml_1                | 	at net.sourceforge.plantuml.stats.StatsUtilsIncrement.onceMoreParse(StatsUtilsIncrement.java:70)
plantuml_1                | 	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:138)
plantuml_1                | 	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:133)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.DiagramResponse.addHeaderForCache(DiagramResponse.java:158)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:99)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.UmlDiagramService.doDiagramResponse(UmlDiagramService.java:93)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.UmlDiagramService.doGet(UmlDiagramService.java:60)
plantuml_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
plantuml_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
plantuml_1                | 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
plantuml_1                | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
plantuml_1                | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
plantuml_1                | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
plantuml_1                | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
plantuml_1                | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
plantuml_1                | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
plantuml_1                | 	at org.eclipse.jetty.server.Server.handle(Server.java:503)
plantuml_1                | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
plantuml_1                | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
plantuml_1                | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
plantuml_1                | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
plantuml_1                | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
plantuml_1                | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
plantuml_1                | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
plantuml_1                | 	at java.lang.Thread.run(Thread.java:748)
plantuml_1                | Jan 03, 2019 7:00:46 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
plantuml_1                | WARNING: Could not lock User prefs.  Unix error code 2.
plantuml_1                | Jan 03, 2019 7:00:46 PM java.util.prefs.FileSystemPreferences syncWorld
plantuml_1                | WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
plantuml_1                | 2019-01-03 19:00:46.846:WARN:oejs.HttpChannel:qtp2027961269-13: /png/U9npoazIqBLJSCp9J4vLi5B8ICt9oUU2y832Ja1PAmNtV0N7yiHABW0XJWoz
plantuml_1                | java.lang.NullPointerException
plantuml_1                | 	at net.sourceforge.plantuml.stats.StatsUtilsIncrement.onceMoreParse(StatsUtilsIncrement.java:70)
plantuml_1                | 	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:138)
plantuml_1                | 	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:133)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.DiagramResponse.addHeaderForCache(DiagramResponse.java:158)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:99)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.UmlDiagramService.doDiagramResponse(UmlDiagramService.java:93)
plantuml_1                | 	at net.sourceforge.plantuml.servlet.UmlDiagramService.doGet(UmlDiagramService.java:60)
plantuml_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
plantuml_1                | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
plantuml_1                | 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
plantuml_1                | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
plantuml_1                | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
plantuml_1                | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
plantuml_1                | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
plantuml_1                | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
plantuml_1                | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
plantuml_1                | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
plantuml_1                | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
plantuml_1                | 	at org.eclipse.jetty.server.Server.handle(Server.java:503)
plantuml_1                | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
plantuml_1                | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
plantuml_1                | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
plantuml_1                | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
plantuml_1                | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
plantuml_1                | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
plantuml_1                | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
plantuml_1                | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
plantuml_1                | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
plantuml_1                | 	at java.lang.Thread.run(Thread.java:748)
```
